# Generated by Django 4.1 on 2022-09-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
